# Generated by Django 2.2.28 on 2022-11-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leadboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
        migrations.AddField(
            model_name='leadboard',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadboard.Players'),
        ),
    ]
